language: php

php:
  - "7.2"
  - "7.3"
  - "7.4"

before_script:
  - composer install

script:
  - echo "Success"
#  - ./vendor/bin/phpunit -v --configuration ./phpunit.xml.dist

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
